Changes from Subversion
We try to create a flexible "Folderish Animation" type which supports
several flavours, e.g. "HTML5 animations" built with Adobe Animate CC/createjs,
or older versions which have been built in ancient times using Flash.

Currently, there is no flexibility at all;
the idea ist to establish an "Animation Type" class to support each
type; when creating a "Folderish Animation", you'd select the type and
then upload the additional files (e.g. Javascript files, images, xml
files) into the new object.
The Animation Types (which don't yet exist) should reside in the
'animations_tool'; currently we can't install the package because of an
AttributeError: AnimationsTool instance has no attribute '_setId'